"""create_tables

Revision ID: ec6fc8286310
Revises: 
Create Date: 2026-09-27 17:00:17.974420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6fc8286310'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS setu")
    op.create_table('merchant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='setu'
    )
    op.create_table('transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('current_status', sa.Enum('PROCESSED', 'SETTLED', 'FAILED', 'INITIATED', name='paymentstatus'), nullable=False),
    sa.Column('last_event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['setu.merchant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='setu'
    )
    op.create_index(op.f('ix_setu_transaction_created_at'), 'transaction', ['created_at'], unique=False, schema='setu')
    op.create_index(op.f('ix_setu_transaction_merchant_id'), 'transaction', ['merchant_id'], unique=False, schema='setu')
    op.create_table('event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('PAYMENT_INITIATED', 'PAYMENT_PROCESSED', 'PAYMENT_FAILED', 'PAYMENT_SETTLED', name='eventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['setu.transaction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='setu'
    )
    op.create_index('idx_transaction_timestamp', 'event', ['transaction_id', 'timestamp'], unique=False, schema='setu', postgresql_include=['event_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transaction_timestamp', table_name='event', schema='setu', postgresql_include=['event_type'])
    op.drop_table('event', schema='setu')
    op.drop_index(op.f('ix_setu_transaction_merchant_id'), table_name='transaction', schema='setu')
    op.drop_index(op.f('ix_setu_transaction_created_at'), table_name='transaction', schema='setu')
    op.drop_table('transaction', schema='setu')
    op.drop_table('merchant', schema='setu')
    # ### end Alembic commands ###
